name: Generate Prediction Chart

on:
  schedule:
   # Australian Grand Prix
    - cron: "0 * 16 3 *"  # Sonntag
    # Chinese Grand Prix
    - cron: "0 * 23 3 *"
    # Japanese Grand Prix
    - cron: "0 * 6 4 *"
    # Bahrain Grand Prix
    - cron: "0 * 13 4 *"
    # Saudi Arabian Grand Prix
    - cron: "0 * 20 4 *"
    # Miami Grand Prix
    - cron: "0 * 4 5 *"
    # Emilia Romagna Grand Prix
    - cron: "0 * 18 5 *"
    # Monaco Grand Prix
    - cron: "0 * 25 5 *"
    # Spanish Grand Prix
    - cron: "0 * 1 6 *"
    # Canadian Grand Prix
    - cron: "0 * 15 6 *"
    # Austrian Grand Prix
    - cron: "0 * 29 6 *"
    # British Grand Prix
    - cron: "0 * 6 7 *"
    # Belgian Grand Prix
    - cron: "0 * 27 7 *"
    # Hungarian Grand Prix
    - cron: "0 * 3 8 *"
    # Dutch Grand Prix
    - cron: "0 * 31 8 *"
    # Italian Grand Prix
    - cron: "0 * 7 9 *"
    # Azerbaijan Grand Prix
    - cron: "0 * 21 9 *"
    # Singapore Grand Prix
    - cron: "0 * 5 10 *"
    # United States Grand Prix
    - cron: "0 * 19 10 *"
    # Mexican Grand Prix
    - cron: "0 * 26 10 *"
    # Brazilian Grand Prix
    - cron: "0 * 9 11 *"
    # Las Vegas Grand Prix
    - cron: "0 * 22 11 *"
    # Qatar Grand Prix
    - cron: "0 * 30 11 *"
    # Abu Dhabi Grand Prix
    - cron: "0 * 7 12 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run chart generator
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python generate_chart.py


      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update prediction chart" || echo "No changes to commit"
          git push
